Models/Entity.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace StoresManagement.Models
{
    public class Entity
    {
        public Entity()
        {
            Branches = new HashSet<Branch>();
            //Customers = new HashSet<Customer>();
        }

        public int Id { get; set; }

        [Display(Name = "Entity Name")]
        public string Name { get; set; }

        public virtual ICollection<Branch> Branches { get; set; }

        //public virtual ICollection<Customer> Customers { get; set; }
    }
}

Controllers/Api/EntitiesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Threading.Tasks;
using System.Web.Http;
using System.Web.Http.Description;
using AutoMapper;
using StoresManagement.Dtos;
using StoresManagement.Models;

namespace StoresManagement.Controllers.Api
{
    public class EntitiesController : ApiController
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET /api/Entities
        public IHttpActionResult GetEntities(string query = null)
        {
            var EntitiesQuery = db.Entities
                .Include(c => c.Branches);

            if (!String.IsNullOrWhiteSpace(query))
                EntitiesQuery = EntitiesQuery.Where(c => c.Name.Contains(query));

            var entityDtos = EntitiesQuery
                .ToList()
                .Select(Mapper.Map<Entity, EntityDto>);

            return Ok(entityDtos);
        }

        // GET /api/Entities/1
        public IHttpActionResult GetEntity(int id)
        {
            var entity = db.Entities.SingleOrDefault(c => c.Id == id);

            if (entity == null)
                return NotFound();

            return Ok(Mapper.Map<Entity, EntityDto>(entity));
        }

        // POST /api/Entities
        [HttpPost]
        public IHttpActionResult CreateEntity(EntityDto entityDto)
        {
            if (!ModelState.IsValid)
                return BadRequest();

            var entity = Mapper.Map<EntityDto, Entity>(entityDto);
            db.Entities.Add(entity);
            db.SaveChanges();

            entityDto.Id = entity.Id;
            return Created(new Uri(Request.RequestUri + "/" + entity.Id), entityDto);
        }

        // PUT /api/Entities/1
        [HttpPut]
        public IHttpActionResult UpdateEntity(int id, EntityDto entityDto)
        {
            if (!ModelState.IsValid)
                return BadRequest();

            var entityInDb = db.Entities.SingleOrDefault(c => c.Id == id);

            if (entityInDb == null)
                return NotFound();

            Mapper.Map(entityDto, entityInDb);

            db.SaveChanges();

            return Ok();
        }

        // DELETE /api/Entities/1
        [HttpDelete]
        public IHttpActionResult DeleteEntity(int id)
        {
            var entityInDb = db.Entities.SingleOrDefault(c => c.Id == id);

            if (entityInDb == null)
                return NotFound();

            db.Entities.Remove(entityInDb);
            db.SaveChanges();

            return Ok();
        }

        //// GET: api/Entities
        //public IEnumerable<EntityDto> GetEntities()
        //{
        //    return db.Entities.AsQueryable().Select(Mapper.Map<Entity, EntityDto>);
        //}

        //// GET: api/Entities/5
        //[ResponseType(typeof(Entity))]
        //public IHttpActionResult GetEntity(int id)
        //{
        //    Entity entity = db.Entities.Find(id);
        //    if (entity == null)
        //    {
        //        return NotFound();
        //    }

        //    return Ok(Mapper.Map<Entity, EntityDto>(entity));
        //}

        //// Edit/Update Entity
        //// PUT: api/Entities/5
        //[ResponseType(typeof(void))]
        //public IHttpActionResult PutEntity(int id, Entity entity)
        //{
        //    if (!ModelState.IsValid)
        //    {
        //        return BadRequest(ModelState);
        //    }

        //    if (id != entity.Id)
        //    {
        //        return BadRequest();
        //    }

        //    db.Entry(entity).State = Entitiestate.Modified;

        //    try
        //    {
        //        db.SaveChanges();
        //    }
        //    catch (DbUpdateConcurrencyException)
        //    {
        //        if (!EntityExists(id))
        //        {
        //            return NotFound();
        //        }
        //        else
        //        {
        //            throw;
        //        }
        //    }

        //    return StatusCode(HttpStatusCode.NoContent);
        //}

        //// Create Entity
        //// POST: api/Entities
        //[ResponseType(typeof(EntityDto))]
        //public async Task<IHttpActionResult> PostBook(Entity entity)
        //{
        //    if (!ModelState.IsValid)
        //    {
        //        return BadRequest(ModelState);
        //    }

        //    db.Entities.Add(entity);
        //    await db.SaveChangesAsync();

        //    // New code:
        //    // Load author name
        //    // db.Entry(entity).Reference(x => x.Author).Load();

        //    var dto = new EntityDto()
        //    {
        //        Id = entity.Id,
        //        Name = entity.Name
        //    };

        //    return CreatedAtRoute("DefaultApi", new { id = entity.Id }, dto);
        //}

        //// DELETE: api/Entities/5
        //[ResponseType(typeof(Entity))]
        //public IHttpActionResult DeleteEntity(int id)
        //{
        //    Entity entity = db.Entities.Find(id);
        //    if (entity == null)
        //    {
        //        return NotFound();
        //    }

        //    db.Entities.Remove(entity);
        //    db.SaveChanges();

        //    return Ok(entity);
        //}

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        private bool EntityExists(int id)
        {
            return db.Entities.Count(e => e.Id == id) > 0;
        }
    }
}

Controllers/EntitiesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using StoresManagement.Models;

namespace StoresManagement.Controllers
{
    public class EntitiesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Entities
        public ActionResult Index()
        {
            return View(db.Entities.ToList());
        }

        // GET: Entities/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Entity entity = db.Entities.Find(id);
            if (entity == null)
            {
                return HttpNotFound();
            }
            return View(entity);
        }

        // GET: Entities/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Entities/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name")] Entity entity)
        {
            if (ModelState.IsValid)
            {
                db.Entities.Add(entity);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(entity);
        }

        // GET: Entities/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Entity entity = db.Entities.Find(id);
            if (entity == null)
            {
                return HttpNotFound();
            }
            return View(entity);
        }

        // POST: Entities/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name")] Entity entity)
        {
            if (ModelState.IsValid)
            {
                db.Entry(entity).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(entity);
        }

        // GET: Entities/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Entity entity = db.Entities.Find(id);
            if (entity == null)
            {
                return HttpNotFound();
            }
            return View(entity);
        }

        // POST: Entities/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Entity entity = db.Entities.Find(id);
            db.Entities.Remove(entity);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/Entities/Create.cshtml
@model StoresManagement.Models.Entity

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Entity</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/Entities/Delete.cshtml
@model StoresManagement.Models.Entity

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Entity</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Views/Entities/Details.cshtml
@model StoresManagement.Models.Entity

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Entity</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Views/Entities/Edit.cshtml
@model StoresManagement.Models.Entity

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Entity</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/Entities/Index.cshtml
@model IEnumerable<StoresManagement.Models.Entity>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>


@*
    Note: I've set the model for this view to IEnumerable<Entity>.
    This is a simple interface implemented by the list class. Since
    in this view we only want to iterate over this list, and we don't
    need any of the operations in the List class (eg Add, Remove, etc),
    it's better to use the IEnumerable interface, which allows use to
    iterate over the list. If in the future, we replace the List with a
    different data structure, as long as it is enumerable, our view code
    will remain unchanged.
*@


<p>
    @Html.ActionLink("New Entity", "Create", "Entities", null, new { @class = "btn btn-primary" })
</p>

<table id="entities" class="table table-bordered table-hover">
    <thead>
        <tr>
            <th>Entity</th>
            @*<th>Membership Type</th>*@
            <th>Delete</th>
        </tr>
    </thead>
    <tbody></tbody>
</table>

@section scripts
{
    <script>
        $(document).ready(function () {
            var table = $("#entities").DataTable({
                ajax: {
                    url: "/api/entities",
                    dataSrc: ""
                },
                columns: [
                    {
                        data: "name",
                        render: function (data, type, entity) {
                            return "<a href='/entities/edit/" + entity.id + "'>" + entity.name + "</a>";
                        }
                    },
                    //{
                    //    data: "membershipType.name"
                    //},
                    {
                        data: "id",
                        render: function (data) {
                            return "<button class='btn-link js-delete' data-entity-id=" + data + ">Delete</button>";
                        }
                    }
                ]
            });

            $("#entities").on("click", ".js-delete", function () {
                var button = $(this);

                bootbox.confirm("Are you sure you want to delete this entity?", function (result) {
                    if (result) {
                        $.ajax({
                            url: "/api/entities/" + button.attr("data-entity-id"),
                            method: "DELETE",
                            success: function () {
                                table.row(button.parents("tr")).remove().draw();
                            }
                        });
                    }
                });
            });
        });
    </script>
}